.catalog:
  name: "Sonarr"
  version: 2.0.0.5322
  description: Smart PVR for newsgroup and bittorrent users
  uuid: 0
  minimum_rancher_version: 2.3.5
  questions: #Used to request user input for configuration options
